config/routes.rb
Rails.application.routes.draw do
  get 'home/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ActiveRecord::Base
  self.table_name = "Users"


  def self.search(search_id, search_name,search_from,search_to)


    where('id = ? OR name = ? OR (birthday BETWEEN ? AND ?)',
          search_id,search_name,search_from,search_to)
  end



  # def self.search(search_id, search_name,search_from,search_to)
  #   us = Home.order(:id)
  #   us = us.where("id = ?", search_id) if search_id.present?
  #   us = us.where("name = ?", search_name) if search_name.present?
  #   us = us.where("birthday >= ?", search_from) if search_from.present?
  #   us = us.where("birthday <= ?", search_to) if search_to.present?
  #   us
  # end


#   def self.search(search_id, search_name,search_from,search_to)
#     @s ||= find_user
#   end
#
# private
#
#   def find_products
#     products = Product.order(:name) # selecl all from DB fisrt, then do the filter below
#     products = products.where("name like ?", "%#{keywords}%") if keywords.present?
#     products = products.where(category_id: category_id) if category_id.present?
#     products = products.where("price >= ?", min_price) if min_price.present?
#     products = products.where("price <= ?", max_price) if max_price.present?
#     products # return
#   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def search

    # if params[:from].present?
    @s = Home.search(params[:id],params[:name],params[:from],params[:to]).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/search.html.erb
<h1>Home#search</h1>
<p>Find me in app/views/home/search.html.erb</p>

<%= form_tag home_search_path, method: :get do %>
  <%= text_field_tag :id, params[:id] %>
  <%= text_field_tag :name, params[:name] %>
  <%= text_field_tag :from, params[:from] %>
  <%= text_field_tag :to, params[:to] %>
  <%= submit_tag "Search", name: nil %>
<% end %>



<h3 class=''>Employees</h3>
          <table id='employee-table' class="table table-hover">
            <thead  class="thead-light">
              <tr>
                <th>Name</th>
                <th>id</th>
                <th>Birthday </th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @s.each do |employee| %>
                <tr>
                  <td><%= employee.name %></td>
                  <td><%= employee.id %></td>
                  <td><%= employee.birthday %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>